services:
  todo-app:
    container_name: 'todo-app'
    build:
      dockerfile: 'Dockerfile'
    image: 'todo-app:latest'
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    links:
      - "postgres"
      - "postgres:database"
      - "postgres:postgres"
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'